STRYKER_RUN_COMMAND = 'dotnet stryker'
STRYKER_COMMAND_PROJECT_ARGUMENT_KEY = '--project'
STRYKER_COMMAND_CONFIG_FILE_ARGUMENT_KEY = '--config-file'

STRYKER_MULTI_PROJECTS_CONFIG_JSON_KEY = 'stryker-multi-projects-config'
STRYKER_MULTI_PROJECTS_CONFIG_PROJECTS_TO_TEST_JSON_KEY = 'projects-to-test'
STRYKER_MULTI_PROJECTS_CONFIG_TEST_PROJECT_PATH_JSON_KEY = 'test-project-path'
STRYKER_MULTI_PROJECTS_CONFIG_STRYKER_CONFIG_FILE_JSON_KEY = 'stryker-config-file'

STRYKER_CONFIG_JSON_KEY = 'stryker-config'
STRYKER_CONFIG_THRESHOLDS_JSON_KEY = 'thresholds'
STRYKER_CONFIG_THRESHOLDS_BREAK_JSON_KEY = 'break'

STRYKER_REPORT_FOLDER_NAME = 'StrykerOutput'
STRYKER_REPORT_FILE_NAME = 'mutation-report.json'
STRYKER_REPORT_FILE_JSON_KEY = 'files'
STRYKER_REPORT_SCHEMA_VERSION_JSON_KEY = 'schemaVersion'
STRYKER_REPORT_THRESHOLDS_JSON_KEY = 'thresholds'
STRYKER_REPORT_THRESHOLDS_HIGH_JSON_KEY = 'high'
STRYKER_REPORT_THRESHOLDS_LOW_JSON_KEY = 'low'
STRYKER_REPORT_FILE_MUTANTS_JSON_KEY = 'mutants'
STRYKER_REPORT_FILE_MUTANTS_ID_JSON_KEY = 'id'
STRYKER_REPORT_FILE_MUTANTS_STATUS_JSON_KEY = 'status'
STRYKER_REPORT_MUTANT_DETECTED_STATUSES = ['Timeout', 'Killed']
STRYKER_REPORT_MUTANT_UNDETECTED_STATUSES = ['Survived', 'NoCoverage']
